### ISSUE TITLE
TODO Comments on tickgit.com

### ISSUE THREAD

**Issue by patrickdevivo** [integration-system/gds#1]
Hi there! I noticed you have a link in the README to tickgit.com! I just wanted to let you know we have support for badges:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/integration-system/gds)](https://www.tickgit.com/browse?repo=github.com/integration-system/gds)

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/integration-system/gds)](https://www.tickgit.com/browse?repo=github.com/integration-system/gds)
```

And also let you know that `todos.tickgit.com` now forwards to `www.tickgit.com`. We have many more features planned, I hope you find the project interesting. Feel free to let me know what ways we can improve it if you have suggestions!

Thanks so much

**Comment by pymq** [comment]
Thanks, @patrickdevivo, badge looks quite well!
